// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsRequest) Reset() {
	*x = GetPostStatsRequest{}
	mi := &file_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsRequest) ProtoMessage() {}

func (x *GetPostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         int64                  `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int64                  `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsResponse) Reset() {
	*x = PostStatsResponse{}
	mi := &file_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsResponse) ProtoMessage() {}

func (x *PostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsResponse.ProtoReflect.Descriptor instead.
func (*PostStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PostStatsResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *PostStatsResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PostStatsResponse) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type GetDynamicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicsRequest) Reset() {
	*x = GetDynamicsRequest{}
	mi := &file_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicsRequest) ProtoMessage() {}

func (x *GetDynamicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicsRequest.ProtoReflect.Descriptor instead.
func (*GetDynamicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetDynamicsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetDynamicsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetDynamicsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type DailyStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStat) Reset() {
	*x = DailyStat{}
	mi := &file_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStat) ProtoMessage() {}

func (x *DailyStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStat.ProtoReflect.Descriptor instead.
func (*DailyStat) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *DailyStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DynamicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*DailyStat           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicsResponse) Reset() {
	*x = DynamicsResponse{}
	mi := &file_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicsResponse) ProtoMessage() {}

func (x *DynamicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicsResponse.ProtoReflect.Descriptor instead.
func (*DynamicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *DynamicsResponse) GetStats() []*DailyStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      string                 `protobuf:"bytes,1,opt,name=stat_type,json=statType,proto3" json:"stat_type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRequest) Reset() {
	*x = GetTopRequest{}
	mi := &file_proto_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRequest) ProtoMessage() {}

func (x *GetTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRequest.ProtoReflect.Descriptor instead.
func (*GetTopRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopRequest) GetStatType() string {
	if x != nil {
		return x.StatType
	}
	return ""
}

func (x *GetTopRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPost) Reset() {
	*x = TopPost{}
	mi := &file_proto_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPost) ProtoMessage() {}

func (x *TopPost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPost.ProtoReflect.Descriptor instead.
func (*TopPost) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{6}
}

func (x *TopPost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *TopPost) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*TopPost             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsResponse) Reset() {
	*x = TopPostsResponse{}
	mi := &file_proto_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsResponse) ProtoMessage() {}

func (x *TopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsResponse.ProtoReflect.Descriptor instead.
func (*TopPostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopPostsResponse) GetPosts() []*TopPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

type TopUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUser) Reset() {
	*x = TopUser{}
	mi := &file_proto_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUser) ProtoMessage() {}

func (x *TopUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUser.ProtoReflect.Descriptor instead.
func (*TopUser) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{8}
}

func (x *TopUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopUser) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*TopUser             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersResponse) Reset() {
	*x = TopUsersResponse{}
	mi := &file_proto_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersResponse) ProtoMessage() {}

func (x *TopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersResponse.ProtoReflect.Descriptor instead.
func (*TopUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{9}
}

func (x *TopUsersResponse) GetUsers() []*TopUser {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_stats_proto protoreflect.FileDescriptor

const file_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stats.proto\x12\x05stats\".\n" +
	"\x13GetPostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"[\n" +
	"\x11PostStatsResponse\x12\x14\n" +
	"\x05views\x18\x01 \x01(\x03R\x05views\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\x03R\bcomments\"c\n" +
	"\x12GetDynamicsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"5\n" +
	"\tDailyStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\":\n" +
	"\x10DynamicsResponse\x12&\n" +
	"\x05stats\x18\x01 \x03(\v2\x10.stats.DailyStatR\x05stats\"B\n" +
	"\rGetTopRequest\x12\x1b\n" +
	"\tstat_type\x18\x01 \x01(\tR\bstatType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"8\n" +
	"\aTopPost\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\x10TopPostsResponse\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.stats.TopPostR\x05posts\"8\n" +
	"\aTopUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\x10TopUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.stats.TopUserR\x05users2\xb7\x03\n" +
	"\fStatsService\x12D\n" +
	"\fGetPostStats\x12\x1a.stats.GetPostStatsRequest\x1a\x18.stats.PostStatsResponse\x12J\n" +
	"\x14GetPostViewsDynamics\x12\x19.stats.GetDynamicsRequest\x1a\x17.stats.DynamicsResponse\x12J\n" +
	"\x14GetPostLikesDynamics\x12\x19.stats.GetDynamicsRequest\x1a\x17.stats.DynamicsResponse\x12M\n" +
	"\x17GetPostCommentsDynamics\x12\x19.stats.GetDynamicsRequest\x1a\x17.stats.DynamicsResponse\x12<\n" +
	"\vGetTopPosts\x12\x14.stats.GetTopRequest\x1a\x17.stats.TopPostsResponse\x12<\n" +
	"\vGetTopUsers\x12\x14.stats.GetTopRequest\x1a\x17.stats.TopUsersResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_stats_proto_rawDescOnce sync.Once
	file_proto_stats_proto_rawDescData []byte
)

func file_proto_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)))
	})
	return file_proto_stats_proto_rawDescData
}

var file_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_stats_proto_goTypes = []any{
	(*GetPostStatsRequest)(nil), // 0: stats.GetPostStatsRequest
	(*PostStatsResponse)(nil),   // 1: stats.PostStatsResponse
	(*GetDynamicsRequest)(nil),  // 2: stats.GetDynamicsRequest
	(*DailyStat)(nil),           // 3: stats.DailyStat
	(*DynamicsResponse)(nil),    // 4: stats.DynamicsResponse
	(*GetTopRequest)(nil),       // 5: stats.GetTopRequest
	(*TopPost)(nil),             // 6: stats.TopPost
	(*TopPostsResponse)(nil),    // 7: stats.TopPostsResponse
	(*TopUser)(nil),             // 8: stats.TopUser
	(*TopUsersResponse)(nil),    // 9: stats.TopUsersResponse
}
var file_proto_stats_proto_depIdxs = []int32{
	3, // 0: stats.DynamicsResponse.stats:type_name -> stats.DailyStat
	6, // 1: stats.TopPostsResponse.posts:type_name -> stats.TopPost
	8, // 2: stats.TopUsersResponse.users:type_name -> stats.TopUser
	0, // 3: stats.StatsService.GetPostStats:input_type -> stats.GetPostStatsRequest
	2, // 4: stats.StatsService.GetPostViewsDynamics:input_type -> stats.GetDynamicsRequest
	2, // 5: stats.StatsService.GetPostLikesDynamics:input_type -> stats.GetDynamicsRequest
	2, // 6: stats.StatsService.GetPostCommentsDynamics:input_type -> stats.GetDynamicsRequest
	5, // 7: stats.StatsService.GetTopPosts:input_type -> stats.GetTopRequest
	5, // 8: stats.StatsService.GetTopUsers:input_type -> stats.GetTopRequest
	1, // 9: stats.StatsService.GetPostStats:output_type -> stats.PostStatsResponse
	4, // 10: stats.StatsService.GetPostViewsDynamics:output_type -> stats.DynamicsResponse
	4, // 11: stats.StatsService.GetPostLikesDynamics:output_type -> stats.DynamicsResponse
	4, // 12: stats.StatsService.GetPostCommentsDynamics:output_type -> stats.DynamicsResponse
	7, // 13: stats.StatsService.GetTopPosts:output_type -> stats.TopPostsResponse
	9, // 14: stats.StatsService.GetTopUsers:output_type -> stats.TopUsersResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_stats_proto_init() }
func file_proto_stats_proto_init() {
	if File_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_proto = out.File
	file_proto_stats_proto_goTypes = nil
	file_proto_stats_proto_depIdxs = nil
}
